name: favoriteLinks

on:
  push:
    tags:
      - "**"

jobs:
  Release_addon:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: make sure we have the correct tag information
        run: git fetch --tags --force

      - name: Obtain tag message
        uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data

      - name: Check differences to master branch
        id: differences-to-master
        run: |
          if git diff origin/master --exit-code; then
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          fi

      - name: abort if tag is not applied on top of master
        if: ${{ steps.differences-to-master.outputs.changes_exist == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Releases can be generated only from commit on head of master branch')

      - name: install system dependencies
        run: sudo apt install gettext

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python dependencies
        run: |
          pip install scons
          pip install markdown

      - name: generate addon
        run: |
          rm -f *.nvda-addon || true
          scons

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.nvda-addon"
          body: "${{ steps.tag-data.outputs.git-tag-annotation }}"
          fail_on_unmatched_files: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
